apiVersion: apps/v1
kind: Deployment
metadata:
  name: expenseai-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expenseai-api
  template:
    metadata:
      labels:
        app: expenseai-api
    spec:
      containers:
        - name: api
          image: <ACR_LOGIN_SERVER>/expenseai-api:latest
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: expenseai-secrets
                  key: db-connection
            - name: ConnectionStrings__Redis
              valueFrom:
                secretKeyRef:
                  name: expenseai-secrets
                  key: redis-connection
            - name: JWT__Key
              valueFrom:
                secretKeyRef:
                  name: expenseai-secrets
                  key: jwt-key
            - name: JWT__Issuer
              value: "ExpenseAI"
            - name: JWT__Audience
              value: "ExpenseAI-Users"
            # Add other AI/Key envs as needed
---
apiVersion: v1
kind: Service
metadata:
  name: expenseai-api
spec:
  type: ClusterIP
  selector:
    app: expenseai-api
  ports:
    - port: 80
      targetPort: 80
