apiVersion: apps/v1
kind: Deployment
metadata:
  name: expenseai-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expenseai-redis
  template:
    metadata:
      labels:
        app: expenseai-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: expenseai-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: expenseai-redis
