name: Lint & Format

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Check code format
        run: dotnet format --verify-no-changes src/backend/ExpenseAI.sln

  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: src/frontend/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: src/frontend
      - name: Lint
        run: npm run lint
        working-directory: src/frontend
